package Shapes.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class test extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      graphics.setColor(Color.blue);
      graphics.drawOval(10, 20, 30, 30);
      graphics.setColor(Color.red);
      graphics.drawRect(100, 200, 50, 50);
      {
        graphics.setColor(Color.blue);
        int[] xPoints = {50, 100, 150};
        int[] yPoints = {50, 100, 50};
        graphics.drawPolygon(xPoints, yPoints, 3);
      }
    }
  };
  public void initialize() {
    this.setTitle("test");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }
  public static void main(String[] args) {
    test canvas = new test();
    canvas.initialize();
  }
}
